export interface Env { DB: D1Database; ALLOWED_ORIGIN: string; BOOTSTRAP_SECRET?: string }
type User = { id:number; username:string; full_name:string; role_code:string; department_id:number|null }
const TYPES=new Set(['LATE','EARLY_LEAVE','MORNING_LEAVE','AFTERNOON_LEAVE','FULL_DAY_LEAVE','ANNUAL_LEAVE','MAKEUP_LEAVE'])
const enc=new TextEncoder()
function cors(req:Request,env:Env){const o=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':o===env.ALLOWED_ORIGIN?o:env.ALLOWED_ORIGIN,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type, X-Bootstrap-Secret','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Vary':'Origin'}}
function json(data:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}})}
function hex(b:ArrayBuffer){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bytesHex(b:Uint8Array){return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha(s:string){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
function randomHex(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);return bytesHex(b)}
function cookie(token:string){return `itca_session=${token}; HttpOnly; Secure; SameSite=None; Path=/; Max-Age=28800`}
function clearCookie(){return 'itca_session=; HttpOnly; Secure; SameSite=None; Path=/; Max-Age=0'}
function tokenFrom(req:Request){return (req.headers.get('Cookie')||'').match(/(?:^|;\s*)itca_session=([^;]+)/)?.[1]||null}
async function currentUser(req:Request,env:Env){const t=tokenFrom(req);if(!t)return null;const th=await sha(t);return env.DB.prepare(`SELECT u.id,u.username,u.full_name,r.code role_code,u.department_id FROM SESSIONS s JOIN USERS u ON u.id=s.user_id JOIN ROLES r ON r.id=u.role_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.active=1`).bind(th).first<User>()}
function manager(u:User){return u.role_code==='ADMIN'||u.role_code==='TRUONG_PHONG'}
export default {async fetch(req:Request,env:Env):Promise<Response>{const h=cors(req,env);if(req.method==='OPTIONS')return new Response(null,{headers:h});const url=new URL(req.url);try{
 if(url.pathname==='/api/health')return json({ok:true,service:'itca-mangement-api',version:'2.0'},200,h)
 if(url.pathname==='/api/auth/bootstrap'&&req.method==='POST'){if(!env.BOOTSTRAP_SECRET||req.headers.get('X-Bootstrap-Secret')!==env.BOOTSTRAP_SECRET)return json({message:'Forbidden'},403,h);const count=await env.DB.prepare('SELECT COUNT(*) n FROM USERS').first<{n:number}>();if((count?.n||0)>0)return json({message:'Hệ thống đã có người dùng'},409,h);const b=await req.json<{username:string;password:string;full_name:string}>();if(!b.username||!b.password||b.password.length<8)return json({message:'Thông tin bootstrap không hợp lệ'},400,h);const salt=randomHex(16),ph=await passwordHash(b.password,salt);await env.DB.prepare(`INSERT INTO DEPARTMENTS(code,name) VALUES('ITCA','ITCA') ON CONFLICT(code) DO NOTHING`).run();const role=await env.DB.prepare(`SELECT id FROM ROLES WHERE code='ADMIN'`).first<{id:number}>();const dep=await env.DB.prepare(`SELECT id FROM DEPARTMENTS WHERE code='ITCA'`).first<{id:number}>();await env.DB.prepare(`INSERT INTO USERS(username,password_hash,password_salt,full_name,department_id,role_id) VALUES(?,?,?,?,?,?)`).bind(b.username,ph,salt,b.full_name,dep!.id,role!.id).run();return json({ok:true},201,h)}
 if(url.pathname==='/api/auth/login'&&req.method==='POST'){const b=await req.json<{username?:string;password?:string}>();const row=await env.DB.prepare(`SELECT u.id,u.username,u.full_name,u.password_hash,u.password_salt,r.code role_code,u.department_id FROM USERS u JOIN ROLES r ON r.id=u.role_id WHERE u.username=? AND u.active=1`).bind((b.username||'').trim()).first<any>();if(!row||!row.password_salt||await passwordHash(b.password||'',row.password_salt)!==row.password_hash)return json({message:'Tên đăng nhập hoặc mật khẩu không đúng'},401,h);const token=randomHex(),th=await sha(token);await env.DB.prepare(`INSERT INTO SESSIONS(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+8 hours'))`).bind(th,row.id).run();delete row.password_hash;delete row.password_salt;return json({user:row},200,{...h,'Set-Cookie':cookie(token)})}
 if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const t=tokenFrom(req);if(t)await env.DB.prepare('DELETE FROM SESSIONS WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{...h,'Set-Cookie':clearCookie()})}
 const u=await currentUser(req,env);if(!u)return json({message:'Unauthorized'},401,h)
 if(url.pathname==='/api/auth/me')return json({user:u},200,h)
 if(url.pathname==='/api/users'&&req.method==='GET'){const q=manager(u)?`SELECT u.id,u.full_name,u.username,r.code role_code,d.name department FROM USERS u JOIN ROLES r ON r.id=u.role_id LEFT JOIN DEPARTMENTS d ON d.id=u.department_id WHERE u.active=1 ORDER BY u.full_name`:`SELECT u.id,u.full_name,u.username,r.code role_code,d.name department FROM USERS u JOIN ROLES r ON r.id=u.role_id LEFT JOIN DEPARTMENTS d ON d.id=u.department_id WHERE u.id=${u.id}`;const r=await env.DB.prepare(q).all();return json({items:r.results},200,h)}
 if(url.pathname==='/api/daily-work/today'&&req.method==='PUT'){const b=await req.json<{work_content?:string;work_mode?:string}>();if(!b.work_content?.trim())return json({message:'Nội dung công việc là bắt buộc'},400,h);await env.DB.prepare(`INSERT INTO DAILY_WORK(user_id,work_date,work_content,work_mode) VALUES(?,date('now'),?,?) ON CONFLICT(user_id,work_date) DO UPDATE SET work_content=excluded.work_content,work_mode=excluded.work_mode,updated_at=datetime('now')`).bind(u.id,b.work_content.trim(),b.work_mode||'OFFICE').run();return json({ok:true},200,h)}
 if(url.pathname==='/api/dashboard/today'&&req.method==='GET'){const rows=await env.DB.prepare(`SELECT u.id,u.full_name,r.code role_code,d.name department,w.work_content,w.work_mode,CASE WHEN lr.request_type='LATE' THEN 'LATE' WHEN lr.request_type IS NOT NULL THEN 'LEAVE' WHEN w.work_mode='REMOTE' THEN 'REMOTE' ELSE 'WORKING' END status,lr.expected_minutes FROM USERS u JOIN ROLES r ON r.id=u.role_id LEFT JOIN DEPARTMENTS d ON d.id=u.department_id LEFT JOIN DAILY_WORK w ON w.user_id=u.id AND w.work_date=date('now') LEFT JOIN LEAVE_REQUESTS lr ON lr.user_id=u.id AND lr.status='APPROVED' AND date('now') BETWEEN lr.start_date AND COALESCE(lr.end_date,lr.start_date) WHERE u.active=1 ${manager(u)&&u.department_id?`AND u.department_id=${u.department_id}`:`AND u.id=${u.id}`} ORDER BY u.full_name`).all();return json({items:rows.results},200,h)}
 if(url.pathname==='/api/leave-requests'&&req.method==='GET'){const r=await env.DB.prepare(`SELECT id,request_type,start_date,end_date,start_time,end_time,expected_minutes,reason,status,requested_at,note FROM LEAVE_REQUESTS WHERE user_id=? ORDER BY requested_at DESC LIMIT 100`).bind(u.id).all();return json({items:r.results},200,h)}
 if(url.pathname==='/api/leave-requests'&&req.method==='POST'){const b=await req.json<any>();if(!TYPES.has(b.request_type))return json({message:'Loại yêu cầu không hợp lệ'},400,h);const r=await env.DB.prepare(`INSERT INTO LEAVE_REQUESTS(user_id,request_type,start_date,end_date,start_time,end_time,expected_minutes,reason,return_to_work_date,makeup_leave,handover_to_user_id,note,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'PENDING')`).bind(u.id,b.request_type,b.start_date||null,b.end_date||b.start_date||null,b.start_time||null,b.end_time||null,b.expected_minutes||null,b.reason||null,b.return_to_work_date||null,b.makeup_leave?1:0,b.handover_to_user_id||null,b.note||null).run();return json({id:r.meta.last_row_id},201,h)}
 if(url.pathname==='/api/approvals/pending'&&req.method==='GET'&&manager(u)){const r=await env.DB.prepare(`SELECT lr.*,us.full_name FROM LEAVE_REQUESTS lr JOIN USERS us ON us.id=lr.user_id WHERE lr.status='PENDING' ${u.role_code==='TRUONG_PHONG'&&u.department_id?`AND us.department_id=${u.department_id}`:''} ORDER BY lr.requested_at DESC`).all();return json({items:r.results},200,h)}
 const m=url.pathname.match(/^\/api\/leave-requests\/(\d+)\/(approve|reject)$/);if(m&&req.method==='POST'&&manager(u)){const id=Number(m[1]),action=m[2]==='approve'?'APPROVED':'REJECTED';const b: { comment?: string } =
  await req.json<{ comment?: string }>()
    .catch((): { comment?: string } => ({}));await env.DB.batch([env.DB.prepare(`UPDATE LEAVE_REQUESTS SET status=?,updated_at=datetime('now') WHERE id=?`).bind(action,id),env.DB.prepare(`INSERT INTO LEAVE_APPROVALS(request_id,approver_id,action,comment) VALUES(?,?,?,?)`).bind(id,u.id,action,b.comment||null)]);return json({ok:true,status:action},200,h)}
 if(url.pathname==='/api/stats/personal'){const month=url.searchParams.get('month')||new Date().toISOString().slice(0,7);const r=await env.DB.prepare(`SELECT request_type,COUNT(*) count,COALESCE(SUM(expected_minutes),0) minutes FROM LEAVE_REQUESTS WHERE user_id=? AND status='APPROVED' AND substr(start_date,1,7)=? GROUP BY request_type`).bind(u.id,month).all();return json({month,items:r.results},200,h)}
 if(url.pathname==='/api/stats/department'&&manager(u)){const month=url.searchParams.get('month')||new Date().toISOString().slice(0,7);const r=await env.DB.prepare(`SELECT us.full_name,lr.request_type,COUNT(*) count,COALESCE(SUM(lr.expected_minutes),0) minutes FROM LEAVE_REQUESTS lr JOIN USERS us ON us.id=lr.user_id WHERE lr.status='APPROVED' AND substr(lr.start_date,1,7)=? ${u.role_code==='TRUONG_PHONG'&&u.department_id?`AND us.department_id=${u.department_id}`:''} GROUP BY us.id,lr.request_type ORDER BY us.full_name`).bind(month).all();return json({month,items:r.results},200,h)}
 return json({message:'Not found'},404,h)
 }catch(e){console.error(e);return json({message:'Internal server error'},500,h)}}}
