CREATE TABLE IF NOT EXISTS ROLES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

INSERT OR IGNORE INTO ROLES (code, name)
VALUES
  ('ADMIN', 'Quản trị hệ thống'),
  ('TRUONG_PHONG', 'Trưởng phòng'),
  ('USER', 'Người dùng');

CREATE TABLE IF NOT EXISTS DEPARTMENTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS USERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  avatar_url TEXT,
  department_id INTEGER,
  role_id INTEGER NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (department_id)
    REFERENCES DEPARTMENTS(id),
  FOREIGN KEY (role_id)
    REFERENCES ROLES(id)
);

CREATE TABLE IF NOT EXISTS LEAVE_REQUESTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  request_type TEXT NOT NULL,
  start_date TEXT,
  end_date TEXT,
  start_time TEXT,
  end_time TEXT,
  expected_minutes INTEGER,
  reason TEXT,
  return_to_work_date TEXT,
  makeup_leave INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id)
    REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS LEAVE_APPROVALS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER NOT NULL,
  approver_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  comment TEXT,
  acted_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (request_id)
    REFERENCES LEAVE_REQUESTS(id),
  FOREIGN KEY (approver_id)
    REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id)
    REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS AUDIT_LOGS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id INTEGER,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id)
    REFERENCES USERS(id)
);

CREATE INDEX IF NOT EXISTS IDX_USERS_DEPARTMENT
  ON USERS(department_id);

CREATE INDEX IF NOT EXISTS IDX_LEAVE_USER
  ON LEAVE_REQUESTS(user_id);

CREATE INDEX IF NOT EXISTS IDX_LEAVE_STATUS
  ON LEAVE_REQUESTS(status);

CREATE INDEX IF NOT EXISTS IDX_LEAVE_DATE
  ON LEAVE_REQUESTS(start_date);

CREATE INDEX IF NOT EXISTS IDX_APPROVAL_REQUEST
  ON LEAVE_APPROVALS(request_id);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_USER
  ON NOTIFICATIONS(user_id);
