ALTER TABLE USERS ADD COLUMN password_salt TEXT;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN handover_to_user_id INTEGER;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN note TEXT;

CREATE TABLE IF NOT EXISTS SESSIONS (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS DAILY_WORK (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  work_date TEXT NOT NULL,
  work_content TEXT NOT NULL,
  work_mode TEXT NOT NULL DEFAULT 'OFFICE',
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(user_id, work_date),
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);
CREATE INDEX IF NOT EXISTS IDX_DAILY_WORK_DATE ON DAILY_WORK(work_date);
CREATE INDEX IF NOT EXISTS IDX_SESSION_USER ON SESSIONS(user_id);
